#!/bin/sh

# Decompile an apk and use jd-gui to view the Java source files
# Usage: amprint <AndroidManifest.xml or APK file>

if [ $# -ne 1 ]; then
    echo "Usage: apksrc <APK filename>"
    exit
fi

echo "Decompiling \"$1\"..."

TEMP_DIR_TEMPLATE="/tmp/apksrc_tmp"

# First, clean the temp files generated in last step
rm -vrf "$TEMP_DIR_TEMPLATE"_*

# Second, decompile the apk
tempFolder=`mktemp -d "$TEMP_DIR_TEMPLATE"_XXXXX `
unzip -qo "$1" classes.dex -d $tempFolder
dex2jar $tempFolder/classes.dex
jd-gui $tempFolder/classes_dex2jar.jar 2>/dev/null &

