#!/bin/sh

# Sign APK using JDK tool "jarsigner" and Android test key

if [ $# -lt 1 ]; then
    echo "Usage: apksign <APK filename> [<key alias>]"
    echo "Supported key aliases: test, platform"
    exit
fi

kernel_name=`uname -s`
IS_MAC_OS=false
if [ $kernel_name = "Darwin" ]; then
    IS_MAC_OS=true
fi

if ! $IS_MAC_OS; then # for Linux only
    alias greadlink="readlink"
fi

CMD_REAL_PATH=`greadlink -e "$0"`
if [ $? -ne 0 ]; then
    CMD_REAL_PATH="$0"
fi

CMD_DIR=`dirname "$CMD_REAL_PATH"`

KEY_ALIAS=android.testkey
if [ $# -gt 1 ]; then
    if [ $2 = platform ]; then
        KEY_ALIAS=android.platformkey
    elif [ $2 != test ]; then
        echo "Unknown key alias: $1"
        exit
    fi
fi

KEYSTORE=$CMD_DIR/apk.keystore

echo "Signing \"$1\" with $KEY_ALIAS key..."

# Remove the old signature first (ignore standard output)
zip -d -q $1 "META-INF*" 1>/dev/null
# Sign the unsigned APK
jarsigner -keystore $KEYSTORE -storepass android $1 $KEY_ALIAS

echo Done
